name: Android CI test.

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sail to the gradlew
        run:  cd android/  
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run:  ./gradlew build 
      - name: Test Android
        run:  ./gradlew test 
