name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: gradlew
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.7
    - name: Build with Gradle
      working-directory: ./android
      run: gradle build

